spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    maximum-pool-size: 100
    connection-timeout: 5000
    min-evictable-idle-time-millis: 1800000
    max-wait: 5000
    hikari:
      maxLifetime: 7200000

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  config-location: classpath:mybatis-config.xml

server:
  port:
